from math import *
from src.util.utils import *

DEFAULT_FRAME = 60

# image
SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 960

PLAYER_WIDTH = 100
PLAYER_HEIGHT = 100

BULLET_WIDTH = 40
BULLET_HEIGHT = 40

SANGMIN_WIDTH = 30
SANGMIN_HEIGHT = 30

BUTTON_WIDTH = 140
BUTTON_HEIGHT = 80

SETTING_WIDTH = 80
SETTING_HEIGHT = 80

SOUND_BUTTON_WIDTH = 80
SOUND_BUTTON_HEIGHT = 80

CLOSE_BUTTON_WIDTH = 80
CLOSE_BUTTON_HEIGHT = 80

BACK_BUTTON_WIDTH = 80
BACK_BUTTON_HEIGHT = 80

TOMAIN_BUTTON_WIDTH = 80
TOMAIN_BUTTON_HEIGHT = 80
# in game
PLAYER_SPEED = 0.5
PLAYER_SPECIAL_SPEED = 0.00001
PLAYER_SPECIAL_INIT_BULLET_CNT = 48


x = [normalized(1, tan(i * (360 / PLAYER_SPECIAL_INIT_BULLET_CNT))) for i in range(1, PLAYER_SPECIAL_INIT_BULLET_CNT // 4)]
print(x)
PLAYER_SPECIAL_BULLET_DEGREE = []
PLAYER_SPECIAL_BULLET_DEGREE.extend([(i[0], i[1]) for i in x])
PLAYER_SPECIAL_BULLET_DEGREE.extend([(i[0], -i[1]) for i in x])
PLAYER_SPECIAL_BULLET_DEGREE.extend([(-i[0], i[1]) for i in x])
PLAYER_SPECIAL_BULLET_DEGREE.extend([(-i[0], -i[1]) for i in x])
PLAYER_SPECIAL_BULLET_DEGREE.extend([(1, 0), (-1, 0), (0, 1), (0, -1)])
print(PLAYER_SPECIAL_BULLET_DEGREE)
BULLET_SPEED = 5
SANGMIN_SPEED = 1

SANGMIN_CREATE_TIME_1 = 0.3
SANGMIN_CREATE_TIME_2 = 0.3

PLAYER_INIT_HP = 10
PLAYER_INIT_MAX_XP = 10
PLAYER_INIT_XPOS = (SCREEN_WIDTH - PLAYER_WIDTH) / 2
PLAYER_INIT_YPOS = (SCREEN_HEIGHT - PLAYER_HEIGHT) / 2

